version: '3.8'
services:
  web:
    build: .
    container_name: fastapi-service
    volumes:
      - /home/user/Desktop/personal-projects/customers-shop-task:/app
    environment:
      PORT: 8895
    ports:
      - "8895:8895"
    tty: true
    stdin_open: true
    restart: "no"
